### ISSUE TITLE
🔬 Tracking issue for array cookie support

### ISSUE THREAD

**Issue by alexanderlinne** [tudasc/TypeART#71]
This is a tracking issue for the support of array cookies in TypeART.

### Steps
- [x] Research when and how array cookies are added
- [x] Add test cases for cases where array cookies are expected to be added -> https://github.com/tudasc/TypeART/commit/65684d7912ccbebfce05ac12dae5d587741244ce, https://github.com/tudasc/TypeART/commit/22d8b4f40c018cb89c3e58012525eb77a3fa4d54
- [x] Implementation
  - [x] Finding array cookies -> https://github.com/tudasc/TypeART/commit/d40d567c67e8f8ccaffacb7a1f6a3962057531f5
  - [x] Add array cookie data to existing data structures -> https://github.com/tudasc/TypeART/commit/7781f78e1445e4fc2f2078484dc0269d379833df
  - [x] Consider the padding of array cookies when calculating array element counts -> https://github.com/tudasc/TypeART/commit/0817a3a8296313ca4398d23f6683ce5706f1e2fc
  - [x] In case an array cookie is present, instrument the actual starting address of the array instead of the originally allocated address ->  https://github.com/tudasc/TypeART/pull/73/commits/650b1a395219148fd56ea3aafae1509c96f3e94d
  - [x] ~~Add instrumentation for array cookies~~

### Unresolved Questions
- [x] Should array cookies be instrumented in any way and if so, how? -> for now, only to correctly calculate array sizes

### Array Cookie research
Array cookies are a `size_t` value saving the allocated length of an array. These cookies are allocated under certain conditions when operator new is used to allocate an array.

#### => When are array cookies created?
According to [1], an array cookie is **not** allocated if either of
- "the element type T has a trivial destructor […] and the usual (array) deallocation function […] does not take two arguments" or
- "the `new` operator being used is `::operator new [](size_t, void*)`"

In Clang this is implemented in [`CGCXXABI::requiresArrayCookie`](https://github.com/llvm/llvm-project/blob/llvmorg-10.0.0/clang/lib/CodeGen/CGCXXABI.cpp#L193) using:
- [`CXXNewExpr::doesUsualArrayDeleteWantSize`](https://github.com/llvm/llvm-project/blob/llvmorg-10.0.0/clang/include/clang/AST/ExprCXX.h#L2298) and [`CXXDeleteExpr::doesUsualArrayDeleteWantSize`](https://github.com/llvm/llvm-project/blob/llvmorg-10.0.0/clang/include/clang/AST/ExprCXX.h#L2395) to check whether the delet function takes two arguments.
- [`CXXNewExpr::getAllocatedType`](https://github.com/llvm/llvm-project/blob/llvmorg-10.0.0/clang/include/clang/AST/ExprCXX.h#L2193) as `expr->getAllocatedType().isDestructedType()` to check whether the array element type has a non-trivial destructor.

#### => How are array cookies created?
According to [1]:
- array cookies always have size `sizeof(size_t)`
- if `align` is the maximum alignment of `size_t` and an element of the array and `padding` is the maximum of `sizeof(size_t}` and `align` bytes:
  - "The space allocated for the will be the space required by the array itself plus `padding` bytes"
  - "The cookie will be stored in the `sizeof(size_t)` bytes immediately preceding the array
 In Clang this is implemented in [`ItaniumCXXABI::InitializeArrayCookie`](https://github.com/llvm/llvm-project/blob/llvmorg-10.0.0/clang/lib/CodeGen/ItaniumCXXABI.cpp#L2010).

[1] https://itanium-cxx-abi.github.io/cxx-abi/abi.html#array-cookies
