### ISSUE TITLE
Tracking issue for demo folder

### ISSUE THREAD

**Issue by ahueck** [tudasc/TypeART#76]
The TypeART demo is not properly maintained currently.

### Current status
- Makefile broken w.r.t. compiling and deprecated MPI symbols
- CMakeLists untested/out of date?
- Out of date scripts

## Issues for release 1.6
- [x] Update Makefile to compile examples with TypeART
- [x] Remove deprecated `apply` script
- [x] Fix deprecations for OpenMPI 4 or higher

## Issues (future)
- [x] Update CMakeLists to build examples
- [x] Add demo to CI system
- [ ] Add README.md for demo explanation

**Comment by ahueck** [comment]
Sections w.r.t. LLVM IR level will be removed from the main README, e.g.,

###### Example instrumentation in LLVM intermediate representation (IR)

- C and corresponding LLVM IR code: A simple heap allocation with malloc of a `double`-array. It contains all
  information needed for TypeART:

    ~~~c
    double* pointer = (double*) malloc(n * sizeof(double));
    ~~~

    ~~~llvm
    ; Assume: %size == n * sizeof(double)
    %pointer = call i8* @malloc(i64 %size)
    %pointer_double = bitcast i8* %pointer to double*
    ~~~

- Corresponding TypeART instrumentation:

    ~~~llvm
    ; Assume: %size == n * sizeof(double)
    ; Heap allocation -- %pointer holds the returned pointer value:
    %pointer = call i8* @malloc(i64 %size)
    ; TypeART instrumentation -- compute the number of double-elements:
    %extent = udiv i64 %size, 8
    ; TypeART runtime callback (pointer, type-id, length) -- 6 is the type-id for double:
    call void @__typeart_alloc(i8* %pointer, i32 6, i64 %extent)
    ; Original bitcast:
    %pointer_double = bitcast i8* %pointer to double*
    ~~~
