### ISSUE TITLE
🔬 Tracking issue for MPI type checking

### ISSUE THREAD

**Issue by alexanderlinne** [tudasc/TypeART#77]
The MPI interceptor library does not currently check the type and element count when checking a buffer used as an argument to a MPI call.

### Steps
- [x] Research what MPI types exist and how they can be inspected
- [x] Implementation
  - [x] Add type checking for builtin MPI types -> https://github.com/tudasc/TypeART/commit/b8295b91bb155cd91857b359e828b3ab4e06d829
  - [x] Add the ability to run tests using mpic++ as a compiler and mpirun and FileCheck for execution and verification -> https://github.com/tudasc/TypeART/commit/82c6a6496907bab33645c6450ef665b431df1b19, https://github.com/tudasc/TypeART/commit/2408cacc823d536d052d9d2f2ecef83b2cc11251
  - [x] Add type checking for custom MPI types
  - [x] Add a README explaining whether and how any given MPI function is typechecked

### Research

All MPI types that may be encountered can generally be divided into two categories: builtin MPI types and custom MPI types. Both are represented using a common C++ type `MPI_Datatype`. A list of builtin MPI types for C/C++ can be found [here](https://pages.tacc.utexas.edu/~eijkhout/pcse/html/mpi-data.html#CC++).
For checking a custom MPI type, the functions [`MPI_Type_get_envelope`](https://www.open-mpi.org/doc/v4.1/man3/MPI_Type_get_envelope.3.php) and [`MPI_Type_get_contents`](https://www.open-mpi.org/doc/v4.1/man3/MPI_Type_get_contents.3.php) may be used. `MPI_Type_get_envelope` allows to retrieve the function which was used to create a given type and the number of arguments used while `MPI_Type_get_contents` allows to retrieve the actual arguments passed to the function.
