### ISSUE TITLE
Tracking issue for compiler wrapper

### ISSUE THREAD

**Issue by ahueck** [tudasc/TypeART#80]
Write a compiler wrapper that intercepts the compilation process, and transforms the compiler invocation to apply TypeART.
Targets are multi-file Makefile projects and CMake.

### Usage example
Instead of using the Clang compiler directly, replace it with our wrappers:
`cmake -DCMAKE_C_COMPILER=typeart-clang -DCMAKE_CXX_COMPILER=typeart-clang++ ...`

### TODO
- [x] Make scripts work in MPI context https://github.com/tudasc/TypeART/commit/303724e84ce0ca4e77d5af5aab68cdc1d1234148
- [x] Find required executables through CMake: clang/clang++/opt/llc https://github.com/tudasc/TypeART/commit/3a4c1d6c866ef9d121ff9870306f39e7baa0118d
- [x] Disable script with (environment) flag during CMake config time https://github.com/tudasc/TypeART/commit/eab5701f6cd87adadcc457720c7408c44de4ec0a
- [x] Test against typeart-bench (CI) codes
- [x] lit tests
- [x] wrapper need to respect sanitizer flag, if TypeART was build with them

#### CMake
- mpicc-wrapper fails to set variables with CMakes find_config(MPI). 
    ```
    message(STATUS "LIBS ${MPI_C_LIBRARIES}")
    message(STATUS ${MPI_C_COMPILE_OPTIONS})
    message(STATUS ${MPI_C_COMPILE_OPTIONS})
    message(STATUS ${MPI_C_LINK_FLAGS})
    message(STATUS ${MPIEXEC})  # this is set
    ```
   - This works instead: `target_link_libraries(${target} PUBLIC MPI::MPI_C)`
